### ISSUE TITLE
Add support for numbers and special characters

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/collabedit#3]
**Expected:**
Support for numbers and special characters in the main text editor of this activity

**Comment by quozl** [comment]
Thanks.  It only supports certain keys, rather than all UTF-8 text that may be entered.  See https://github.com/sugarlabs/collabwrapper/blob/master/texteditor.py for an implementation that does not fixate on Gdk level, instead sharing the UTF-8 text.
